### ISSUE TITLE
things are messy…

### ISSUE THREAD

**Issue by fidelthomet** [SensesProject/share#3]
- filenames in `modules/stocktake-1-co2` and `modules/stocktake-2-graphs` do not follow guidelines
- things in `dist/share` should have subfolders in modules
- `previews` should be placed within `modules/[module-name]` and then somehow extracted, or generated based on the stuff that's already in `modules/[module-name]`
- `settings/modules.json` should be humanly readable, i.e.; always have the same order of attributes starting with id and title

**Comment by z3to** [comment]
#2

**Comment by fidelthomet** [comment]
won't fix
